package-lock.json, package.json, src/App.tsx, src/components/Profile/Profile.styles.ts, src/components/Profile/Profile.tsx, src/components/header/header-main/Header.styled.ts, src/components/header/header-main/Header.tsx, src/components/header/header-sub/Header.styled.ts, src/components/header/header-sub/HeaderSub.tsx, src/components/navbar/Navbar.styled.ts, src/components/navbar/Navbar.tsx, src/routes/Router.tsx, src/styles/common.css, src/types/button.ts, src/types/profile.ts
공통 컴포넌트 Header와 Navbar입니다.
고정된 컴포넌트이기에, 사이즈지정은 따로 받지 않았습니다.
header의 경우 추후 경로에 맞게 수정할 필요가 있습니다.
- Header
- Navbar
=> [🎨 HTML&CSS] 공통 컴포넌트 - Header,Navbar

package-lock.json, package.json, src/App.tsx, src/components/LoadingSpinner/Loading.module.ts, src/components/LoadingSpinner/Loading.tsx
loadingspinner 구현
- styled-component 패키지 다운으로 인해 npm i 명령어 필수 
- loadingspinner
=> [feature]:loadingspinner 구현

src/components/Input/Input.tsx, src/components/Textarea/Textarea.tsx, src/styles/common.css, src/styles/reset.css, src/types/form.ts
=> [FEAT] input, textarea 컴포넌트 제작 #14

src/App.tsx, src/components/Profile/Profile.styles.ts, src/components/button/Button.styles.ts, src/components/button/Button.tsx, src/components/header/header-main/Header.styled.ts, src/components/header/header-sub/Header.styled.ts, src/components/header/header-sub/HeaderSub.tsx, src/types/button.ts
Button,Profile 추가 및 header수정 
- Button 컴포넌트와 Profile 컴포넌트를 가져와 globalcss를 적용하였습니다.
- Header 부분 샘이님께서 피드백 주신 부분 반영하였습니다
프로필은 혜련님께서 만드신 것 가져왔어요~~~~
=> [🎨 HTML&CSS] Button,Profile 추가 및 header수정 

index.html, src/components/Modal/Modal.tsx, src/components/Modal/ModalFull.tsx, src/hooks/useScrollLock.ts, src/styles/modal/modal.style.ts, src/styles/modal/modalfull.style.ts, src/types/modal.ts
#11 
- 풀페이지 모달
- 바텀시트
- 오픈되었을 때 body의 스크롤 막기
=> [HTML&CSS] 모달 제작 #11

package-lock.json, src/pages/login/index.tsx
> close #44 
- 액세스토큰 저장했습니다.
- 로그인 test계정은 asd@asd.com / asdasd123으로 해주세요
=> [✨ Feature] 로그인 정보저장 

package-lock.json, package.json, src/components/Layout/Layout.tsx
#54 
> close #54 
tanstack query 세팅
=> [⚙️ Setting] tanstack query 세팅 #54

.gitignore, e2e/tests-examples/demo-todo-app.spec.ts, e2e/tests/example.spec.ts, package-lock.json, package.json, playwright.config.ts, tsconfig.node.json
> close #132 
이렇게 설정하고 설치했습니다
- `test-examples/demo-todo-app.spec.ts `: Playwright가 설치될 때 자동으로 생성되는 샘플 테스트 코드
- tests 폴더아래에 폴더만들어서 .spec.ts 파일 만들어서 작성하시면 됩니다~~
- 저도 처음써봐서ㅎㅎ 설정 잘못된거 있으면 고쳐주세요
```
npx playwright test
npx playwright test email.spec.ts
npx playwright test --ui
```
이렇게 나오면 해당 로컬호스트 들어가면 테스트 보고서를 볼 수있습니다~~
=> [⚙️ Setting] Playwright 세팅

src/apis/userInfoApi.ts, src/component/MyPageType/MyPageSave.tsx, src/component/PlayList/PlayList.styles.ts, src/component/PlayList/PlayList.tsx, src/types/List.ts
> close #121 
- 삭제 아이콘 클릭시 한꺼번에 삭제되던 것을 고쳤습니다
- 삭제 아이콘을 유사한 것으로 변경하였습니다.
제 플레이리스트 어떤가요?
=> [🐛 Bug] 마이페이지 저장 삭제시 전체 다 삭제되는 이슈 #121

playwright.config.ts
> close #132
- playwright 실행할때 오류가 있어서 세팅 수정했습니다.
=> feat: 세팅 수정

src/component/SubscribeList/SubscribeList.tsx, src/component/SubscribeList/SubscriptionListModal.tsx, src/pages/search/index.tsx
> close #125 
[🐛 Bug] 구독한 사람이 없으면 구독한사람이 없다고 처리 및 검색한 내용 없습니다 처리 
- 내용
- 기능
[🐛 Bug] 구독한 사람이 없으면 구독한사람이 없다고 처리 및 검색한 내용 없습니다 처리 
=> [🐛 Bug] 구독한 사람이 없으면 구독한사람이 없다고 처리 및 검색한 내용 없습니다 처리 

src/apis/search/playList/index.ts, src/component/FeedList/FeedList.tsx, src/component/FeedList/FeedListOptionPopUp.tsx, src/component/ToastMessage/toastMessageContainer.module.ts, src/pages/search/index.tsx
> close #122 
-  popup toast message 및 팝업 창 닫기
- 기능
=> [🐛 Bug] popup toast message 및 팝업 창 닫기

src/apis/feed/index.ts, src/apis/search/playList/index.ts, src/component/FeedList/FeedList.tsx, src/component/SubscribeList/AllSubscribePlayLists.tsx, src/component/SubscribeList/SubscribePlayLists.tsx, src/pages/Home.tsx, src/pages/search/index.tsx, src/types/List.ts
> close #126 
- [🐛 Bug] 공개여부에 따라 플리 보여주기
=> [🐛 Bug] 공개여부에 따라 플리 보여주기

src/component/FeedList/FeedList.style.ts, src/component/FeedList/FeedList.tsx, src/types/List.ts
> close #137 
- [🐛 Bug] 플레이리스트 클릭 시 상세 플리로 이동
=> [🐛 Bug] 플레이리스트 클릭 시 상세 플리로 이동

src/component/FeedList/FeedList.style.ts, src/component/FeedList/FeedList.tsx
> close #124 
- [🐛 Bug] 피드 리스트에서 프로필 누를 시 상세 프로필 페이지로 이동 처리
=> [🐛 Bug] 피드 리스트에서 프로필 누를 시 상세 프로필 페이지로 이동 처리

src/apis/feed/index.ts, src/apis/search/playList/index.ts, src/apis/subscribe/playList/index.ts, src/apis/subscribe/subscribePlayList/index.ts, src/component/FeedList/FeedList.style.ts, src/component/SubscribeList/AllSubscribePlayLists.tsx, src/component/SubscribeList/SubscribePlayLists.tsx, src/component/index.ts, src/pages/Home.tsx, src/pages/search/index.tsx
> close #127 
- 스켈레톤 ui을 적절치 못한 사용이 될 수 있다고 판단해서 멘토링에 추가적인 질문으로 기입했습니다.
- 기능
=> [🐛 Bug] 무한 스크롤 이미지 깜빡임 처리

src/apis/userInfoApi.ts, src/component/MyPageType/MyPageLikes.tsx, src/component/MyPageType/MyPageSave.tsx, src/pages/profileEdit/index.tsx
> close #144 
- 좋아요 플레이리스트 삭제시 모든 플레이리스트가 다 삭제되는 현상이 있었습니다.
- 저장된 플레이리스트 삭제 수정처럼 바꿨는데, 매개변수를 playlist[0]으로 주어, 어떤 플레이리스트를 삭제하던간에, 0번째 인덱스의 플레이리스트가 삭제되고 말았습니다.
- handleDelete 함수에 playlist_id를 주고 mutate에 매개변수를 넣어 삭제하고자하는 플레이리스트가 삭제될 수 있도록 변경하였습니다.
저도 테스트코드,,, 시작해보도록 하겠습니다 ,,,
=> [🐛 Bug] 좋아요 옵션 클릭시 한번에 다 삭제되는 이슈

src/component/MyPageType/MyPageLikes.tsx, src/component/MyPageType/MyPageSave.tsx
> close #155 
- 좋아요 /저장 staleTime을 0으로 항상 최신 데이터를 가져오도록 변경하였습니다.
=> [🐛 Bug] 좋아요,저장 즉시 반영 안되는 문제 수정

src/component/FeedList/FeedList.style.ts
> close #117 
- [[🎨 HTML&CSS] 피드 아이템 비율 수정](https://github.com/Dev-FE-2/toy-project3-team1/issues/117)
- 기능
=> [🎨 HTML&CSS] 피드 아이템 비율 수정

.gitignore, e2e/tests/signin.spec.ts, e2e/tests/signup.spec.ts, playwright.config.ts, src/component/SignUp/StepEmail.tsx, src/pages/signIn/index.tsx
> close #113 
- 이메일 로그인
- 이메일 로그인 실패
- 로그인 성공 후 페이지 이동
- 회원가입 
- 이메일 중복, 비밀번호 불일치, 닉네님 유효성검사 실패 테스트 진행했습니다.
=> [✨ Feature] auth playwright 테스트

src/main.tsx, src/pages/signIn/index.tsx, src/routes/Router.tsx
> close #153 
- 소셜로그인시 토스트 두번되는 문제 해결했습니다.
- 비로그인 검사를 더 추가해 ProtectedRoute 를 수정했습니다.
=> [🐛 Bug] 소셜로그인 시 토스트, 비로그인 검사

README.md
=> docs: README 컨벤션 추가

src/component/Comment/CommentModifier.tsx
> close #167 
- mutation 처리 방식을 콜백에서 async/await로 변경
- 토스트 메시지 타입 수정 (success -> error)
=> [🐛 Bug] 댓글 수정시 토스트 안뜨는 이슈

src/component/Modal/ModalFull.tsx, src/component/Search/SearchList.tsx, src/component/SubscribeList/SubscribeList.module.ts, src/component/SubscribeList/SubscriptionListModal.tsx, src/component/header/header-main/Header.tsx, src/component/header/header-sub/HeaderSub.tsx, src/pages/search/index.tsx
> close #166 
[🐛 Bug] 구독 목록 List css 수정
- 내용
- 기능
=> [🐛 Bug] 구독 목록 List css 수정

src/component/Search/SearchList.tsx, src/component/header/header-main/Header.tsx
> close #이슈번호
- [Fix] searchList error 해결
- 기능
=> [Fix] searchList error 해결

src/component/SignOut/SignOutButton.tsx
> close #이슈번호
-feature/logoutconfirmmodal
- 기능
=> feature: logoutconfirmmodal 추가

src/component/FeedList/FeedList.tsx, src/component/FeedList/FeedListOptionPopUp.tsx, src/component/FeedList/Footer.tsx, src/component/SubscribeList/SubscriptionListModal.tsx, src/hooks/useBookmarksMututation.tsx, src/hooks/useDeleteSubscribe.tsx, src/hooks/useSubscribeCreate.tsx, src/hooks/useUpdateLike.tsx
> close #176 
-  useMutaton custom hook으로 수정 
=> [🔄 Refactor] useMutaton custom hook으로 수정 

src/apis/myPlayList/index.ts, src/apis/signup/index.ts, src/component/Navbar/Navbar.styled.ts, src/component/Navbar/Navbar.tsx, src/component/SignUp/StepEmail.tsx, src/hooks/useEmailCheck.ts, src/hooks/useMyPlayList.ts, src/pages/myPlayList/index.tsx, src/pages/playListCreate/index.tsx
> close #이슈번호
- 컴포넌트 분리
- api코드 분리
=> [🔄 Refactor] api코드 수정, 컴포넌트 분리
